import type { PublicWork } from "./portfolio";

export const ART_WORKS: PublicWork[] = [
  {slug:"starry-current",title:"Starry Current",motif:"starry-current",category:"Painterly",preset:"nocturne",rows:40,cols:136,size:1.3,previewVersion:"6",background:"#e5e4dd",accent:"#273b57",
    description:"Cobalt currents curl around warm gold stars. A flowing, painterly night sky, drawn across the whole bracelet.",
    story:"The blue-and-gold contrast and restless curves take inspiration from Van Gogh's night skies. Two asymmetric spirals and a low ribbon of teal make an original composition for the narrow cuff. Short, broken highlights suggest brush marks; every mark is part of the editable bead chart.",
    colors:[["Midnight","#14233d"],["Cobalt","#426a99"],["Indigo","#243c66"],["Star gold","#d0a54e"],["Moonlight","#f4e4a8"],["Blue stroke","#729bba"],["Deep turquoise","#3c8087"],["Pale current","#86bbb6"],["Amber halo","#ba7e39"]],
    finishes:["matte","matte","matte","metal","pearl","matte","matte","matte","matte"]},
  {slug:"sunflower-nocturne",title:"Sunflower Nocturne",motif:"sunflower-nocturne",category:"Botanical",preset:"bloom",rows:40,cols:136,size:1.3,previewVersion:"6",background:"#eee7da",accent:"#5e573d",
    description:"Layered ochre and honey petals, dark seed heads and olive leaves against a deep blue-green ground.",
    story:"Three sunflowers turn at different angles, with a larger bloom at the centre of the cuff. Amber underpainting, pale petal strokes and scattered seeds give the flowers depth. The warm, earthy palette takes its cue from painted sunflower studies, translated into a beadwork composition.",
    colors:[["Petrol canvas","#203c48"],["Honey petal","#e8bb4e"],["Burnt ochre","#a76a32"],["Antique gold","#cf9c45"],["Straw light","#f5d990"],["Olive leaf","#657c57"],["Amber petal","#d78939"],["Deep leaf","#3e5b4a"],["Seed brown","#60442f"]],
    finishes:["matte","matte","matte","metal","matte","matte","matte","matte","matte"]},
  {slug:"azure-rosette",title:"Azure Rosette",motif:"azure-rosette",category:"Geometric",preset:"nocturne",rows:40,cols:136,size:1.3,previewVersion:"6",background:"#e8e8e0",accent:"#334f64",
    description:"Eight-fold rosettes in lapis, porcelain and turquoise, joined by a delicate gold outline.",
    story:"Four complete medallions run around the band. Pale centres and slender turquoise petals sit inside a scalloped gold frame, with small interlocking diamonds filling the corners. The radial symmetry is balanced with a quiet navy ground so that the fine lines stay readable.",
    colors:[["Lapis ground","#172f48"],["Blue enamel","#3a6483"],["Deep cobalt","#274864"],["Champagne gold","#c9ab73"],["Porcelain","#f0e8d5"],["Turquoise","#559b9e"],["Slate line","#627987"],["Pale celadon","#a5c4bb"],["Warm stone","#ad9a78"]],
    finishes:["matte","gloss","matte","metal","pearl","gloss","matte","gloss","matte"]},
  {slug:"gilded-palmette",title:"Gilded Palmette",motif:"gilded-palmette",category:"Geometric",preset:"nocturne",rows:40,cols:136,size:1.3,previewVersion:"6",background:"#e8e5dd",accent:"#374b45",
    description:"Mirrored jade fans and fine champagne spokes on matte charcoal. A restrained Art Deco rhythm.",
    story:"A scalloped outer arc frames each fan. Alternating jade sections, fine gold ribs and small celadon arches give the band a precise left-right balance. Four complete fans keep the composition continuous around the wrist; the matte ground lets the metallic details catch the light.",
    colors:[["Soft charcoal","#222827"],["Jade enamel","#538e83"],["Deep malachite","#2d554e"],["Champagne","#c5a166"],["Pale ivory","#e8ddbd"],["Verdigris","#3c746b"],["Celadon","#a0c8b4"],["Antique jade","#80af9a"],["Olive shadow","#69765b"]],
    finishes:["matte","gloss","matte","metal","pearl","gloss","gloss","gloss","matte"]},
  {slug:"cypress-flame",title:"Cypress Flame",motif:"cypress-flame",category:"Painterly",preset:"nocturne",rows:40,cols:136,size:1.3,background:"#e4e3dc",accent:"#22375e",
    description:"Two dark spires climb out of a gold field under a cobalt sky in long broken brush marks.",
    story:"The whole band is built from short, broken marks rather than flat fills, so the surface keeps moving the way a painted one does. Two cypresses lean in opposite directions as they rise, one tall and one short, and a pale aureole turns in the upper corner. Level strokes near the horizon give way to long leaning stalks further down, which is what makes the field read as a field. This 1.3 mm fine-bead study is a digital prototype, not a physically tested pattern. Make a gauge swatch before committing to the cuff; colours are not linked to manufacturer SKUs.",
    colors:[["Midnight sky","#1a2a4a"],["Cobalt sky","#3f6a9c"],["Indigo bank","#22375e"],["Wheat gold","#d2a54e"],["Aureole","#f0e4b4"],["Cypress green","#33583c"],["Deep cypress","#14291c"],["Cypress light","#79975f"],["Amber field","#b97e33"]],
    finishes:["matte","matte","matte","metal","pearl","matte","matte","matte","matte"]},
  {slug:"wheatfield-crows",title:"Wheatfield Crows",motif:"wheatfield-crows",category:"Painterly",preset:"nocturne",rows:40,cols:136,size:1.3,background:"#e2e1db",accent:"#141d33",
    description:"A storm sky over gold wheat, three earth paths forking from the horizon and crows above the crop.",
    story:"Three paths leave the horizon and fan toward the near edge, so the band has a direction instead of a repeat. The sky is painted in restless dark marks with a paler streak at the horizon, and the crop changes character with distance: level strokes far away, long leaning stalks close up. Six crows hang above the wheat, held just clear of the paler sky so their shape survives being translated into beads. Digital prototype; verify bead size and tension with a swatch.",
    colors:[["Storm slate","#4c5c82"],["Wheat gold","#cfa23f"],["Storm navy","#1b2439"],["Wheat light","#e9c968"],["Pale sky","#93a0c0"],["Earth path","#a8763a"],["Crow black","#07090f"],["Deep wheat","#9c7a34"],["Straw","#d9b46a"]],
    finishes:["matte","matte","matte","metal","matte","matte","matte","matte","matte"]},
  {slug:"violet-irises",title:"Violet Irises",motif:"violet-irises",category:"Botanical",preset:"bloom",rows:40,cols:136,size:1.3,background:"#e9e7d8",accent:"#3a3f6e",
    description:"Four violet irises among long tapered blades on a warm olive ground, one bloom left pale.",
    story:"Every bloom is one heart with three narrow standards standing above it and three broad falls spreading below, and every blade is drawn twice, first in a dark rim and then in leaf green, so no shape frays into stray beads at this scale. Three of the irises are violet and periwinkle; the fourth is left white to break the rhythm. Gold runs down the centre of each blade and the heart of each flower. Digital prototype; make a gauge swatch before committing to the full cuff.",
    colors:[["Olive ground","#66743f"],["Iris periwinkle","#8497cc"],["Deep violet","#3a3f6e"],["Ochre gold","#c9a04a"],["Pale cream","#e8e2c8"],["Leaf green","#7fa05a"],["Deep leaf","#3d6045"],["Lilac","#a184bb"],["Warm ochre","#b98a3c"]],
    finishes:["matte","gloss","matte","metal","pearl","gloss","matte","gloss","matte"]},
  {slug:"blossom-bough",title:"Blossom Bough",motif:"blossom-bough",category:"Botanical",preset:"bloom",rows:40,cols:136,size:1.3,background:"#e6e6de",accent:"#1f3f57",
    description:"Two dark boughs cross a pale teal sky, carrying white blossom with rose undersides.",
    story:"A brighter study than most of the collection: a spring sky, two tapering boughs, twigs branching at intervals and eleven sprays of blossom. Petals that face downward take a rose shade, which gives every flower a light side and a shadowed side without outlining each one. Small buds sit in the gaps where the branches cross. Digital prototype; verify bead size and tension with a swatch before making.",
    colors:[["Teal sky","#6ba3b4"],["Pale sky","#8fc2cc"],["Branch navy","#1f3f57"],["Gold centre","#d9b45f"],["Blossom white","#fbf7ec"],["Deep teal","#4e8798"],["Blossom rose","#e3b6bd"],["Branch light","#2f6b7a"],["Light sky","#b3d9dd"]],
    finishes:["matte","matte","matte","metal","pearl","matte","matte","gloss","matte"]},
];
