import type { PublicWork } from "./portfolio";
import type { OriginalMotif } from "./original-patterns";

type Study = { slug:string;title:string;motif:OriginalMotif;category:PublicWork["category"];colors:string[];names:string[];description:string;story:string;rows?:number;cols?:number;size?:number;finishes?:PublicWork["finishes"];previewVersion?:string };
const studies:Study[] = [
  {slug:"camellia-nocturne",title:"Camellia Nocturne",motif:"camellia-fine",category:"Botanical",rows:40,cols:136,size:1.3,previewVersion:"4",finishes:["matte","matte","matte","metal","pearl","matte","matte","matte","matte"],colors:["#263c36","#c58491","#955469","#bea36d","#f4d9cf","#6e8b68","#e2b2b5","#405e4c","#9aa981"],names:["Pine ink","Tea rose","Mulberry fold","Old gold","Petal ivory","Sage leaf","Blush silk","Deep fern","Leaf light"],description:"Three layered camellias, a closed bud and veined leaves on deep pine. A fine-bead botanical study in nine softly shaded colours.",story:"Redrawn bead by bead across a 40 × 136 grid, with three differently sized flowers rather than a tiled icon. Overlapping petal whorls move from mulberry shadows through tea rose and blush to ivory tips; pointed, two-tone leaves follow a winding stem. This 1.3 mm fine-bead study is a digital prototype, not a physically tested pattern. Match bead sizes and make a gauge swatch before committing to the full cuff; colours are not linked to manufacturer SKUs."},
  {slug:"pocket-puppy",title:"Pocket Puppy",motif:"puppy",category:"Whimsical",rows:40,cols:136,size:1.3,previewVersion:"5",colors:["#f1e6d3","#b97855","#74473d","#c9a35f","#fff4de","#78927b","#d99a9e"],names:["Vanilla","Caramel","Cocoa","Honey","Muzzle cream","Sage","Rosy collar"],description:"A floppy-eared puppy with a rosy collar, soft paws and tiny stars on a warm vanilla ground.",story:"A large round face keeps the puppy recognisable at fine bead scale. Dark floppy ears, a small muzzle and a collar give the silhouette character without copying a branded mascot. Digital prototype; test a gauge swatch first."},
  {slug:"orbiting-cat",title:"Orbiting Cat",motif:"space-cat",category:"Whimsical",rows:40,cols:136,size:1.3,previewVersion:"5",colors:["#26354d","#8aa5c5","#4f678d","#c4a36b","#f2ead8","#8fae9b","#c18fb0"],names:["Night blue","Sky glass","Orbit blue","Moon gold","Starlight","Mint","Cosmic pink"],description:"A curious cat in a glass helmet, floating among stars, moons and mint-coloured orbit lines.",story:"The helmet, ears, whiskers and reflective glass are built from individual beads for a playful, contemporary silhouette. Digital prototype; bead size and tension should be verified with a swatch."},
  {slug:"cloud-bear",title:"Cloud Bear",motif:"cloud-bear",category:"Whimsical",rows:40,cols:136,size:1.3,previewVersion:"5",colors:["#e7edf0","#aab8c0","#667681","#c5a46b","#fff6df","#8aa487","#d98fa0"],names:["Cloud white","Blue grey","Slate","Soft gold","Cream","Meadow","Coral scarf"],description:"A sleepy cloud bear with rounded ears, a tiny rainbow scarf and floating sparkle marks.",story:"Rounded ears and a soft cloud outline make this bear feel gentle and modern. The four-bead scarf adds a small burst of colour without making the pattern noisy. Digital prototype; verify scale with a gauge swatch."},
  {slug:"rainbow-balloons",title:"Rainbow Balloons",motif:"rainbow-balloons",category:"Whimsical",rows:40,cols:136,size:1.3,previewVersion:"5",colors:["#f5eadc","#df8f8a","#d8ad62","#7e9e91","#86a5c5","#9b83ad","#4e5c58"],names:["Paper cream","Coral","Honey","Sage","Sky","Lilac","Ink ribbon"],description:"Three glossy balloons tied with dancing ribbons, centered by a small golden star.",story:"The balloons are intentionally oversized and separated with negative space, so their highlights read clearly on the fine grid. Ribbons meet at a golden star to give the repeat a memorable focal point. Digital prototype; check physical tension before making."},
  {slug:"porcelain-tulips",title:"Porcelain Tulips",motif:"tulips",category:"Botanical",colors:["#f0eadd","#6584a0","#35536f","#b6a079","#fff9ed","#819684","#acc7d3"],names:["Porcelain","Delft blue","Indigo","Pale brass","Milk","Willow","Blue mist"],description:"Two blue tulips rise at different heights on porcelain cream, with slender willow-green leaves.",story:"The paired flowers have pointed crowns and pale interior strokes. Their offset heights give the band a gentle rhythm without a busy background. Blue and green are separated by a warm cream ground and a narrow brass selvedge."},
  {slug:"woodland-fox",title:"Woodland Fox",motif:"fox",category:"Whimsical",colors:["#eee7d7","#bb774e","#503f39","#b49a65","#fff3da","#81907a","#dca889"],names:["Oat linen","Cinnamon","Walnut","Brass","Vanilla","Moss","Apricot"],description:"Tiny cinnamon fox faces with cream cheeks and moss sprigs, on a quiet oat-coloured band.",story:"Upright ears, two dark eyes and a pointed cream muzzle make the fox readable at bead scale. The drawing is deliberately spare, with a small gold accent below each face and green sprigs at its sides. No branded character or external illustration is used."},
  {slug:"moonlit-rabbit",title:"Moonlit Rabbit",motif:"rabbit",category:"Whimsical",colors:["#54556f","#a3a2ba","#353245","#c6af76","#f3edde","#879b94","#dbaab3"],names:["Dusk violet","Lavender","Blackberry","Moon gold","Moonmilk","Eucalyptus","Ballet pink"],description:"Cream rabbits, soft pink ears and small crescent moons on a dusky violet ground.",story:"Long ears and tiny cheek accents give this repeat its expression. A crescent sits beside each rabbit rather than above it, keeping the composition compact across the bracelet. The pale body needs a darker ground to stay clear."},
  {slug:"silk-ribbon",title:"Silk Ribbon",motif:"bows",category:"Whimsical",colors:["#eee4da","#a9657a","#704357","#b8a078","#fff4e7","#89968b","#deb3bb"],names:["Almond","Dusty rose","Plum silk","Champagne","Cream","Grey sage","Ribbon pink"],description:"Rose-coloured bows with folded tails and pale inner loops, spaced along an almond ground.",story:"Broad triangular loops narrow into a darker knot. Pale inner folds make the ribbon feel layered while the forked tails remain legible on the staggered grid. Tiny gold diamonds connect the bows without filling the surrounding space."},
  {slug:"strawberry-tea",title:"Strawberry Tea",motif:"strawberries",category:"Botanical",colors:["#f1e9da","#b76070","#854959","#b7a071","#fff2d7","#6d8870","#e1b0a4"],names:["Tea cream","Berry rose","Jam","Honey gold","Seed cream","Strawberry leaf","Peach"],description:"Rose-red strawberries with cream seeds and leafy crowns, bordered with honey gold.",story:"Each berry tapers to a point and carries a small, irregular arrangement of light seeds. A darker edge adds volume without introducing extra colours. The crowns and scattered cream dots keep the repeating fruit light and playful."},
  {slug:"lily-bells",title:"Lily Bells",motif:"bells",category:"Botanical",colors:["#536e65","#bbc9b2","#314e45","#baa477","#f3eddd","#93aa85","#d5dfc7"],names:["Laurel","Pale leaf","Deep fern","Soft gold","Ivory bell","Meadow","Celadon"],description:"Three ivory bell flowers hang from fine green stems on a laurel-coloured band.",story:"A curved sequence of bells is balanced by two long leaves. The open ground gives the small flowers room, while a few gold beads suggest the opening of each bell. This design favours a clear light-on-dark palette over elaborate shading."},
  {slug:"swan-reverie",title:"Swan Reverie",motif:"swans",category:"Whimsical",colors:["#768c9c","#bac9d3","#364755","#baa073","#f6eee0","#a5b9b7","#d4cfc5"],names:["Lake blue","Blue haze","Ink","Reed gold","Feather cream","Water mint","Warm grey"],description:"Small cream swans with curved necks and delicate wing strokes float above mint-coloured ripples.",story:"The raised neck, pointed beak and sloping tail distinguish each bird with very few beads. Two short water lines anchor the drawing, and a small star balances the empty space beside the neck. Keep the wing strokes close to the feather colour for a softer finish."},
  {slug:"butterfly-silk",title:"Butterfly Silk",motif:"butterflies",category:"Whimsical",colors:["#eee8dd","#a38cac","#6d5b81","#b8a078","#fff4e5","#8b9c8c","#c7b8cd"],names:["Silk cream","Orchid","Violet shadow","Antique gold","Pearl light","Sage","Lilac"],description:"Orchid butterflies with dark wing outlines, lilac lower wings and fine gold bodies.",story:"Large upper wings and smaller lower lobes give this butterfly a recognisable silhouette. Pale marks near the tips separate the layered wing colours. The paired wings are drawn on the actual staggered bead grid, with a narrow border framing the repeat."},
  {slug:"cherry-sunday",title:"Cherry Sunday",motif:"cherries",category:"Botanical",colors:["#f0e6d6","#b85f70","#7f4159","#b7a16e","#fff1dc","#758c70","#e4aaa9"],names:["Custard","Cherry","Morello","Honey","Clotted cream","Stem green","Pink glint"],description:"Pairs of shaded cherries hang from slender stems on a warm custard ground.",story:"The fruit sits at slightly different heights, linked by one stem junction and a long leaf. Small pink highlights soften the deep cherry edges. Sparse gold accents give the playful motif a more restrained jewellery-like finish."},
  {slug:"starlit-lace",title:"Starlit Lace",motif:"lace",category:"Geometric",colors:["#304849","#759994","#203638","#b7a371","#eee9d8","#537873","#b6cec5"],names:["Peacock ink","Jade","Deep teal","Old gold","Linen light","Patina","Pale jade"],description:"Fine gold lozenges surround jade and linen centres on a peacock-green band.",story:"Two fine diamond outlines surround a small, elongated centre. The distance between the outlines creates a lace-like rhythm with relatively few colours. A pair of light beads joins neighbouring repeats, keeping the structure continuous around the band."},
  {slug:"catnap-garden",title:"Catnap Garden",motif:"cats",category:"Whimsical",colors:["#e4e9dd","#a99684","#57494a","#b3a071","#f5ecdb","#82967b","#d5a3a3"],names:["Garden mist","Biscuit","Cocoa","Soft brass","Milk","Sage","Rose cheek"],description:"Sleepy biscuit-coloured cats with pale faces and rosy cheeks, nestled between sage sprigs.",story:"Closed eyes give these little cats a quiet expression. A biscuit outline frames the pale face and pointed ears, while a tiny rosy nose keeps the drawing warm. The motif is an original bead-scale animal study, not an adaptation of a character."},
];

export const ORIGINAL_WORKS:PublicWork[] = studies.map(study=>({
  ...study,preset:"coast",rows:study.rows??28,cols:study.cols??112,
  background:study.motif === "camellia-fine" ? "#e8e6dd" : study.colors[0],accent:study.colors[2],
  colors:study.colors.map((hex,i)=>[study.names[i],hex]),
}));
