import type { PublicWork } from "./portfolio";
import type { OriginalMotif } from "./original-patterns";

type Study = { slug:string;title:string;motif:OriginalMotif;category:PublicWork["category"];colors:string[];names:string[];description:string;story:string;rows?:number;cols?:number;size?:number;finishes?:PublicWork["finishes"];previewVersion?:string };
const studies:Study[] = [
  {slug:"camellia-nocturne",title:"Camellia Nocturne",motif:"camellia-fine",category:"Botanical",rows:40,cols:136,size:1.3,previewVersion:"4",finishes:["matte","matte","matte","metal","pearl","matte","matte","matte","matte"],colors:["#263c36","#c58491","#955469","#bea36d","#f4d9cf","#6e8b68","#e2b2b5","#405e4c","#9aa981"],names:["Pine ink","Tea rose","Mulberry fold","Old gold","Petal ivory","Sage leaf","Blush silk","Deep fern","Leaf light"],description:"Three layered camellias, a closed bud and veined leaves on deep pine. A fine-bead botanical study in nine softly shaded colours.",story:"Redrawn bead by bead across a 40 × 136 grid, with three differently sized flowers rather than a tiled icon. Overlapping petal whorls move from mulberry shadows through tea rose and blush to ivory tips; pointed, two-tone leaves follow a winding stem. This 1.3 mm fine-bead study is a digital prototype, not a physically tested pattern. Match bead sizes and make a gauge swatch before committing to the full cuff; colours are not linked to manufacturer SKUs."},
  {slug:"porcelain-tulips",title:"Porcelain Tulips",motif:"tulips",category:"Botanical",colors:["#f0eadd","#6584a0","#35536f","#b6a079","#fff9ed","#819684","#acc7d3"],names:["Porcelain","Delft blue","Indigo","Pale brass","Milk","Willow","Blue mist"],description:"Two blue tulips rise at different heights on porcelain cream, with slender willow-green leaves.",story:"The paired flowers have pointed crowns and pale interior strokes. Their offset heights give the band a gentle rhythm without a busy background. Blue and green are separated by a warm cream ground and a narrow brass selvedge."},
  {slug:"lily-bells",title:"Lily Bells",motif:"bells",category:"Botanical",colors:["#536e65","#bbc9b2","#314e45","#baa477","#f3eddd","#93aa85","#d5dfc7"],names:["Laurel","Pale leaf","Deep fern","Soft gold","Ivory bell","Meadow","Celadon"],description:"Three ivory bell flowers hang from fine green stems on a laurel-coloured band.",story:"A curved sequence of bells is balanced by two long leaves. The open ground gives the small flowers room, while a few gold beads suggest the opening of each bell. This design favours a clear light-on-dark palette over elaborate shading."},
  {slug:"starlit-lace",title:"Starlit Lace",motif:"lace",category:"Geometric",colors:["#304849","#759994","#203638","#b7a371","#eee9d8","#537873","#b6cec5"],names:["Peacock ink","Jade","Deep teal","Old gold","Linen light","Patina","Pale jade"],description:"Fine gold lozenges surround jade and linen centres on a peacock-green band.",story:"Two fine diamond outlines surround a small, elongated centre. The distance between the outlines creates a lace-like rhythm with relatively few colours. A pair of light beads joins neighbouring repeats, keeping the structure continuous around the band."},
  {slug:"koi-drift",title:"Koi Drift",motif:"koi",category:"Whimsical",rows:40,cols:136,size:1.3,colors:["#1f4855","#d1553f","#16303c","#c9a45c","#f0ece0","#5c8560","#e9b9ae","#31513f","#8fb8bd"],names:["Deep water","Vermilion","Ink shadow","Gold","Ivory","Pad green","Blush","Deep green","Pale ripple"],description:"Two carp turn through a band of moving water, with lily pads, a lotus and rising bubbles. A fine-bead study in nine shaded colours.",story:"The pair is drawn at different depths: a large ivory carp with vermilion markings leads, a smaller one follows closer to the pads. Water is suggested by four flowing lines and flattened ripples rather than by a flat background, so the eye keeps moving along the band. This 1.3 mm fine-bead study is a digital prototype, not a physically tested pattern. Make a gauge swatch before committing to the full cuff; colours are not linked to manufacturer SKUs."},
  {slug:"peacock-plume",title:"Peacock Plume",motif:"peacock",category:"Whimsical",rows:40,cols:136,size:1.3,colors:["#1e2b46","#2f7fb5","#101a2e","#c9a45c","#f2ead8","#2f8a63","#b07534","#1d5238","#8fc9b4"],names:["Indigo night","Peacock blue","Ink blue","Gold","Cream","Emerald","Bronze","Deep green","Pale teal"],description:"Five peacock eyes fan across an indigo ground, each ringed in bronze and gold with hair-fine emerald fringe.",story:"Every eye is built from the centre out: an ink-blue heart, peacock blue, bronze, then gold, with barbules that widen as they travel outwards. The five plumes sit on a shallow arc and lean away from one another, so the fan keeps its shape around the wrist. Small gold stars fill the gaps near the selvedge. Digital prototype; verify bead size and tension with a swatch."},
  {slug:"deco-sunburst",title:"Deco Sunburst",motif:"deco-fan",category:"Geometric",rows:40,cols:136,size:1.3,colors:["#efe7d6","#22201f","#dcc490","#b8912f","#f8f3e6","#2f7d68","#1d4f43"],names:["Ivory","Onyx","Champagne","Gold","Cream","Jade","Deep jade"],description:"An Art Deco fan in onyx, gold and jade: concentric bands, radiating seams and stepped jambs framing a faceted crown.",story:"The whole composition radiates from a single point below the band, so the arcs stay true however long the cuff becomes. Alternating onyx and jade bands carry the contrast, while champagne rays cross the outer ivory ring. Stepped jambs close both ends symmetrically. Digital prototype; check physical tension before making."},
  {slug:"fern-unfurling",title:"Fern Unfurling",motif:"fern",category:"Botanical",rows:40,cols:136,size:1.3,colors:["#152119","#579468","#2e5a42","#c9a45c","#e6e0cb","#86bd79","#b5d18f","#6f9f6d"],names:["Forest ink","Fern green","Deep fern","Old gold","Cream","New growth","Light frond","Sage"],description:"Three fern fronds unrolling into tight croziers, each with paired leaflets along the stem and gold spores in the open ground.",story:"A crozier is the whole point of the study: the youngest part of a fern is a single ribbon rolled in on itself, and a spiral stays legible even when one turn is only two beads across. Each of the three fronds is coiled at a different tension, so the band moves from a nearly closed fist to a frond almost ready to open. Darker green lines the outside of every curve and the newest growth sits pale at the heart. This 1.3 mm fine-bead study is a digital prototype, not a physically tested pattern. Make a gauge swatch before committing to the full cuff; colours are not linked to manufacturer SKUs."},
  {slug:"zellige-star",title:"Zellige Star",motif:"zellige",category:"Geometric",rows:40,cols:136,size:1.3,colors:["#141b33","#2f5f9e","#0b1122","#c9a45c","#f0e8d6","#1f7a6a","#b07534","#173c4d"],names:["Indigo night","Sapphire","Ink","Gold","Ivory","Emerald","Copper","Petrol"],description:"Eight-point zellige stars interlock across an indigo ground: sapphire and emerald points, gold outlines and small copper knots at every seam.",story:"Every star is the union of two squares, one turned forty-five degrees, so its outline stays geometrically exact at any size. Adjacent stars meet exactly at their side points, and a small star knots each seam to hold the lattice together. Inside, a nested ivory star and a petrol core give the eye a place to land. The whole band is a true twenty-eight column repeat. Digital prototype; verify bead size and tension with a swatch."},
  {slug:"lunar-sequence",title:"Lunar Sequence",motif:"lunar",category:"Minimal",rows:22,cols:112,colors:["#111628","#e6e8f0","#333d63","#c9a45c","#f4f1e6","#8fa3c8","#202844"],names:["Night indigo","Moon silver","Shade indigo","Gold","Moon ivory","Pale blue","Slate edge"],description:"Eight moon phases in sequence on a night ground, each disc ringed in gold with small silver stars in the gaps.",story:"The band walks the full lunar month from new moon to waning crescent with nothing but a disc, a gold rim and a terminator. The dark limb uses a shade of indigo rather than the ground, so even a new moon keeps its circle on the wrist. Four-point stars sit in the intervals and a slate edge frames the sequence. Digital prototype; check physical tension before making."},
];

export const ORIGINAL_WORKS:PublicWork[] = studies.map(study=>({
  ...study,preset:"coast",rows:study.rows??28,cols:study.cols??112,
  background:study.motif === "camellia-fine" ? "#e8e6dd" : study.colors[0],accent:study.colors[2],
  colors:study.colors.map((hex,i)=>[study.names[i],hex]),
}));
